// Code generated by protoc-gen-go. DO NOT EDIT.
// source: security.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	// value of username when want login
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// value of password when want login
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55a487c716a8b59c, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetUserInfoRequest struct {
	// this user uuid MSB which want to get
	Msb uint64 `protobuf:"varint,1,opt,name=msb,proto3" json:"msb,omitempty"`
	// this user uuid LSB which want to get
	Lsb                  uint64   `protobuf:"varint,2,opt,name=lsb,proto3" json:"lsb,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoRequest) Reset()         { *m = GetUserInfoRequest{} }
func (m *GetUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoRequest) ProtoMessage()    {}
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55a487c716a8b59c, []int{1}
}

func (m *GetUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoRequest.Unmarshal(m, b)
}
func (m *GetUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoRequest.Merge(m, src)
}
func (m *GetUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoRequest.Size(m)
}
func (m *GetUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoRequest proto.InternalMessageInfo

func (m *GetUserInfoRequest) GetMsb() uint64 {
	if m != nil {
		return m.Msb
	}
	return 0
}

func (m *GetUserInfoRequest) GetLsb() uint64 {
	if m != nil {
		return m.Lsb
	}
	return 0
}

type Error struct {
	// info code of system
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// info field error
	Field string `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	// information error message
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_55a487c716a8b59c, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Response struct {
	// data is JSON
	// for example : if you calling login this will send json token etc...
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_55a487c716a8b59c, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "github.tawakhal.openapi.proto.LoginRequest")
	proto.RegisterType((*GetUserInfoRequest)(nil), "github.tawakhal.openapi.proto.GetUserInfoRequest")
	proto.RegisterType((*Error)(nil), "github.tawakhal.openapi.proto.Error")
	proto.RegisterType((*Response)(nil), "github.tawakhal.openapi.proto.Response")
}

func init() { proto.RegisterFile("security.proto", fileDescriptor_55a487c716a8b59c) }

var fileDescriptor_55a487c716a8b59c = []byte{
	// 621 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xdf, 0x4e, 0x13, 0x4d,
	0x14, 0x67, 0xb7, 0x94, 0x8f, 0x6f, 0x3e, 0xf8, 0xc4, 0xd1, 0xc4, 0xa6, 0x82, 0x4e, 0x36, 0x1a,
	0x0d, 0x42, 0xb7, 0x2d, 0x31, 0x81, 0xc6, 0x18, 0x8b, 0x7f, 0x10, 0xd4, 0x40, 0x16, 0x1a, 0x23,
	0x77, 0xb3, 0xed, 0x61, 0x3b, 0xb2, 0x9d, 0x19, 0x67, 0x66, 0xa9, 0x85, 0x70, 0xe3, 0x13, 0x18,
	0x4c, 0xbc, 0xd0, 0x07, 0xf0, 0x81, 0x7c, 0x05, 0x9f, 0xc2, 0x2b, 0xb3, 0xd3, 0x5d, 0x02, 0x69,
	0x22, 0x5c, 0xcd, 0xf9, 0xf3, 0x3b, 0xe7, 0xfc, 0xce, 0xef, 0x0c, 0xfa, 0x5f, 0x43, 0x3b, 0x51,
	0xcc, 0x0c, 0x2a, 0x52, 0x09, 0x23, 0xf0, 0x5c, 0xc4, 0x4c, 0x37, 0x09, 0x2b, 0x86, 0xf6, 0xe9,
	0x7e, 0x97, 0xc6, 0x15, 0x21, 0x81, 0x53, 0xc9, 0x86, 0xe9, 0xf2, 0x6c, 0x24, 0x44, 0x14, 0x83,
	0x4f, 0x25, 0xf3, 0x29, 0xe7, 0xc2, 0x50, 0xc3, 0x04, 0xd7, 0x59, 0x76, 0xc1, 0x3e, 0xed, 0xc5,
	0x08, 0xf8, 0xa2, 0xee, 0xd3, 0x28, 0x02, 0xe5, 0x0b, 0x69, 0x11, 0xa3, 0x68, 0xef, 0x05, 0x9a,
	0x7a, 0x2d, 0x22, 0xc6, 0x03, 0xf8, 0x90, 0x80, 0x36, 0xb8, 0x8c, 0x26, 0x13, 0x0d, 0x8a, 0xd3,
	0x1e, 0x94, 0x1c, 0xe2, 0xdc, 0xff, 0x37, 0x38, 0xf5, 0xd3, 0x9c, 0xa4, 0x5a, 0xf7, 0x85, 0xea,
	0x94, 0xdc, 0x61, 0x2e, 0xf7, 0xbd, 0x65, 0x84, 0xd7, 0xc0, 0xb4, 0x34, 0xa8, 0x75, 0xbe, 0x27,
	0xf2, 0x6e, 0x33, 0xa8, 0xd0, 0xd3, 0xa1, 0x6d, 0x34, 0x1e, 0xa4, 0x66, 0x1a, 0x89, 0x75, 0x68,
	0xcb, 0xc7, 0x83, 0xd4, 0xf4, 0x5e, 0xa1, 0xe2, 0x73, 0xa5, 0x84, 0xc2, 0x18, 0x8d, 0xb7, 0x45,
	0x67, 0x38, 0xb6, 0x18, 0x58, 0x1b, 0x5f, 0x47, 0xc5, 0x3d, 0x06, 0x71, 0x3e, 0x6f, 0xe8, 0xe0,
	0x12, 0xfa, 0xa7, 0x07, 0x5a, 0xd3, 0x08, 0x4a, 0x05, 0x1b, 0xcf, 0x5d, 0xef, 0x16, 0x9a, 0x0c,
	0x40, 0x4b, 0xc1, 0x35, 0xa4, 0xfd, 0x3a, 0xd4, 0xd0, 0x6c, 0x0d, 0x6b, 0xd7, 0x7f, 0x14, 0xd0,
	0x95, 0xed, 0x4c, 0xec, 0x6d, 0x50, 0x07, 0xac, 0x0d, 0xf8, 0xb7, 0x83, 0x8a, 0x56, 0x03, 0xfc,
	0xa0, 0xf2, 0x57, 0xe1, 0x2b, 0x67, 0x95, 0x2a, 0xdf, 0xbb, 0x00, 0x9c, 0xf3, 0xf0, 0xbe, 0x39,
	0x27, 0xcd, 0xc3, 0xf2, 0x7f, 0x2d, 0x6e, 0x92, 0x7d, 0x62, 0x5b, 0xcc, 0x17, 0x6a, 0xf5, 0xa5,
	0xfa, 0x0c, 0x95, 0x32, 0x66, 0x6d, 0x7b, 0x0e, 0xff, 0xbd, 0x16, 0xbc, 0x31, 0x12, 0xd9, 0x58,
	0x41, 0x85, 0x7a, 0xb5, 0x8a, 0xeb, 0x5e, 0x15, 0x8d, 0x24, 0xf1, 0xec, 0x91, 0x97, 0x2e, 0xe5,
	0x35, 0x88, 0xc7, 0x34, 0x23, 0x46, 0xec, 0x03, 0x27, 0x1d, 0xa6, 0x19, 0x67, 0xde, 0x71, 0x50,
	0x7c, 0xb9, 0xb3, 0xb3, 0xb5, 0x1d, 0x8e, 0x7d, 0xfa, 0xf9, 0xeb, 0x8b, 0x7b, 0xc3, 0xc3, 0xfe,
	0x41, 0xcd, 0xcf, 0xff, 0x99, 0x1f, 0xa7, 0x34, 0x1a, 0xce, 0x3c, 0xfe, 0xea, 0xa0, 0xab, 0x67,
	0x0e, 0xb7, 0x3a, 0x68, 0xb5, 0xd6, 0x9f, 0xe1, 0xda, 0x05, 0xbb, 0x8d, 0x9e, 0xfa, 0xf2, 0x72,
	0xdc, 0xb5, 0x84, 0x6e, 0xe3, 0xb9, 0x73, 0x84, 0xd2, 0x4f, 0xe6, 0x1f, 0xf5, 0x74, 0x78, 0xec,
	0x1f, 0xc5, 0x3a, 0x3c, 0x5e, 0xfd, 0xee, 0x9e, 0x34, 0x3f, 0xbb, 0x98, 0xa3, 0x9b, 0x9b, 0x12,
	0x38, 0x69, 0x6e, 0xad, 0x93, 0x44, 0x33, 0x1e, 0x91, 0xb5, 0x60, 0xeb, 0x29, 0x59, 0xa3, 0x06,
	0xfa, 0x74, 0xe0, 0x6d, 0xa0, 0xe9, 0xcd, 0x38, 0x62, 0x64, 0x27, 0x1b, 0x8a, 0xef, 0x74, 0x8d,
	0x91, 0xba, 0xe1, 0xfb, 0x19, 0x9b, 0xb6, 0xe8, 0xf9, 0x39, 0x23, 0x3f, 0x65, 0xb4, 0x48, 0x25,
	0x2b, 0x5f, 0x33, 0xb4, 0x9f, 0x46, 0x56, 0x1e, 0x3e, 0x89, 0x7a, 0x94, 0xc5, 0x29, 0xac, 0x5e,
	0xa8, 0x55, 0xaa, 0xde, 0xf4, 0x39, 0x56, 0xf3, 0xae, 0xe3, 0x5e, 0xe6, 0x4e, 0xbb, 0xef, 0xd0,
	0x5b, 0x34, 0x11, 0x02, 0x55, 0xa0, 0xf0, 0x9b, 0x49, 0x17, 0x2f, 0x37, 0x13, 0xd3, 0x05, 0x6e,
	0x32, 0xd0, 0xf0, 0x36, 0x0b, 0x44, 0x2a, 0xd8, 0x63, 0x1f, 0xa1, 0x43, 0xc2, 0x01, 0x59, 0xb5,
	0xe8, 0x46, 0xf6, 0x92, 0x47, 0x16, 0xf2, 0xb8, 0x3c, 0x9d, 0x56, 0x0a, 0xc5, 0x0e, 0x87, 0x85,
	0x6e, 0x38, 0x85, 0xd0, 0x69, 0xeb, 0xb1, 0xdd, 0xa2, 0x55, 0x33, 0x9c, 0xb0, 0xcf, 0xd2, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x1e, 0x27, 0x82, 0x3a, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SecurityServiceClient is the client API for SecurityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SecurityServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Response, error)
	GetUserInfoByUUID(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*Response, error)
}

type securityServiceClient struct {
	cc *grpc.ClientConn
}

func NewSecurityServiceClient(cc *grpc.ClientConn) SecurityServiceClient {
	return &securityServiceClient{cc}
}

func (c *securityServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/github.tawakhal.openapi.proto.SecurityService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityServiceClient) GetUserInfoByUUID(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/github.tawakhal.openapi.proto.SecurityService/GetUserInfoByUUID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecurityServiceServer is the server API for SecurityService service.
type SecurityServiceServer interface {
	Login(context.Context, *LoginRequest) (*Response, error)
	GetUserInfoByUUID(context.Context, *GetUserInfoRequest) (*Response, error)
}

func RegisterSecurityServiceServer(s *grpc.Server, srv SecurityServiceServer) {
	s.RegisterService(&_SecurityService_serviceDesc, srv)
}

func _SecurityService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.tawakhal.openapi.proto.SecurityService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityService_GetUserInfoByUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityServiceServer).GetUserInfoByUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.tawakhal.openapi.proto.SecurityService/GetUserInfoByUUID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityServiceServer).GetUserInfoByUUID(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SecurityService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "github.tawakhal.openapi.proto.SecurityService",
	HandlerType: (*SecurityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _SecurityService_Login_Handler,
		},
		{
			MethodName: "GetUserInfoByUUID",
			Handler:    _SecurityService_GetUserInfoByUUID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "security.proto",
}
